hero = {
		["attack_min"] = 5,
		["attack_max"] = 6,
		["magic_attack"] = 5,
		["level"] = 5,
		["defense"] = 25,
		["magic_defense"] = 25,
		["hp"] = 100,
		["hp_max"] = 100,
		["mp"] = 15,
		["mp_max"] = 15,
		["exp"] = 0,
		["exp_to_level"] = 500,
		["speed"] = 75,
		["crit_hit"] = 5,
		["resistence"] = {
			["melee"] = 0,
			["ranged"] = 0,
			["magic"] = 0,
			["fire"] = 0,
			["ice"] = 0,
			["thunder"] = 0,
			["water"] = 0,
			["sancta"] = 0,
			["dark"] = 0,
			["ade"] = 0
		},
		["equip"] = {
			["Weapon"] = "",
			["Hands"] = "",
			["Chest"] = "",
			["Shield"] = "",
			["Hair"] = "",
			["Foots"] = "",
			["Accessory"] = "",
		}
}